from __future__ import annotations

import secrets
from datetime import datetime, timedelta, timezone

from celery.result import AsyncResult
from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse, RedirectResponse
from pydantic import BaseModel

from app.card.generator import generate_card
from app.celery_app import celery_app
from app.config import settings
from app.db.supabase_client import get_supabase
from app.models.profile import AnalysisResult

router = APIRouter()


class ShareRequest(BaseModel):
    job_id: str


def _extract_success_result(job_id: str) -> AnalysisResult:
    result = AsyncResult(job_id, app=celery_app)
    if result.status != "SUCCESS":
        # 425 Too Early — job is still running or result has expired.
        # Using a real 4xx so axios throws and the frontend catch handler fires.
        raise HTTPException(
            status_code=425,
            detail={"status": result.status, "message": "Analysis result not ready. Try again shortly."},
        )
    payload = result.result
    if not isinstance(payload, dict):
        raise HTTPException(status_code=404, detail="Result payload missing")
    return AnalysisResult.model_validate(payload)


def _to_utc(dt_text: str) -> datetime:
    normalized = dt_text.replace("Z", "+00:00")
    dt = datetime.fromisoformat(normalized)
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


@router.post("/share")
async def create_share(request: ShareRequest) -> dict[str, str]:
    payload = _extract_success_result(request.job_id)

    if payload.card_url and payload.share_token:
        token = payload.share_token
        card_url = payload.card_url
        expires_at = payload.expires_at or (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        og_url = f"{settings.og_base_url}/api/og/{token}" if settings.API_BASE_URL else f"{settings.frontend_origin}/shared/{token}"
        return {
            "token": token,
            "card_url": card_url,
            "url": og_url,
            "expires_at": expires_at,
        }

    fingerprint = payload.fingerprint
    narrative = payload.narrative

    supabase = get_supabase()
    token = secrets.token_urlsafe(16)
    card_path = f"cards/{token}.png"
    png_bytes = generate_card(fingerprint, narrative)

    supabase.storage.from_(settings.SUPABASE_STORAGE_BUCKET).upload(
        card_path,
        png_bytes,
        {"content-type": "image/png", "cache-control": "604800"},
    )
    card_url = supabase.storage.from_(settings.SUPABASE_STORAGE_BUCKET).get_public_url(card_path)

    expires_at = (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
    supabase.table("share_tokens").insert(
        {
            "token": token,
            "username": fingerprint.username,
            "card_url": card_url,
            "expires_at": expires_at,
        }
    ).execute()

    og_url = f"{settings.og_base_url}/api/og/{token}" if settings.API_BASE_URL else f"{settings.frontend_origin}/shared/{token}"
    return {
        "token": token,
        "card_url": card_url,
        "url": og_url,
        "expires_at": expires_at,
    }


@router.get("/og/{token}", response_class=HTMLResponse)
async def share_og_page(token: str) -> HTMLResponse:
    """Crawler-visible page with OG meta tags; redirects humans to the SPA."""
    supabase = get_supabase()
    response = supabase.table("share_tokens").select("card_url, username, expires_at").eq("token", token).limit(1).execute()
    data = response.data if hasattr(response, "data") else None
    if not data:
        raise HTTPException(status_code=404, detail="Share token not found")

    row = data[0]
    card_url = row.get("card_url", "")
    username = row.get("username", "")
    spa_url = f"{settings.frontend_origin}/shared/{token}"
    title = f"{username} on GridPath"
    description = "A GitHub developer fingerprint generated by GridPath."

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{title}</title>
  <meta name="description" content="{description}" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="{title}" />
  <meta property="og:description" content="{description}" />
  <meta property="og:image" content="{card_url}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{title}" />
  <meta name="twitter:description" content="{description}" />
  <meta name="twitter:image" content="{card_url}" />
  <meta http-equiv="refresh" content="0;url={spa_url}" />
  <script>window.location.replace("{spa_url}")</script>
</head>
<body>
  <p>Redirecting to <a href="{spa_url}">{title}</a>…</p>
</body>
</html>"""
    return HTMLResponse(content=html)


@router.get("/card/{token}")
async def get_card_redirect(token: str) -> RedirectResponse:
    supabase = get_supabase()
    response = supabase.table("share_tokens").select("token, card_url, expires_at").eq("token", token).limit(1).execute()
    data = response.data if hasattr(response, "data") else None
    if not data:
        raise HTTPException(status_code=404, detail="Share token not found")

    row = data[0]
    expires_at = row.get("expires_at")
    card_url = row.get("card_url")
    if not isinstance(expires_at, str) or not isinstance(card_url, str):
        raise HTTPException(status_code=404, detail="Share token invalid")

    if _to_utc(expires_at) < datetime.now(timezone.utc):
        raise HTTPException(status_code=410, detail="Share token expired")

    return RedirectResponse(url=card_url, status_code=302)
