import { useEffect, useMemo, useState } from "react"
import { Link, useParams } from "react-router-dom"

import { GlassPanel } from "../components/ui/GlassPanel"
import { supabase } from "../lib/supabase"

type SharedRow = {
  card_url: string
  username: string
  expires_at: string
}

function upsertMeta(selector: string, attr: "name" | "property", key: string, content: string) {
  const existing = document.head.querySelector(selector) as HTMLMetaElement | null
  const meta = existing || document.createElement("meta")
  meta.setAttribute(attr, key)
  meta.setAttribute("content", content)
  if (!existing) {
    document.head.appendChild(meta)
  }
}

export default function Shared() {
  const { token = "" } = useParams()
  const [row, setRow] = useState<SharedRow | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    const load = async () => {
      // supabase-js returns errors as values, not throws — always destructure both.
      const { data, error } = await supabase
        .from("share_tokens")
        .select("card_url, username, expires_at")
        .eq("token", token)
        .single()

      if (!cancelled) {
        if (error) {
          // PGRST116 = "0 rows" — treat as not-found rather than a server error.
          const msg =
            error.code === "PGRST116"
              ? "This share link does not exist or has been removed."
              : "We could not load this shared card right now."
          setError(msg)
        } else {
          setRow((data as SharedRow | null) || null)
        }
        setLoading(false)
      }
    }

    void load()
    return () => {
      cancelled = true
    }
  }, [token])

  const expired = useMemo(() => {
    if (!row) return true
    return new Date(row.expires_at).getTime() < Date.now()
  }, [row])

  useEffect(() => {
    if (!row || expired) return
    document.title = `${row.username} on GridPath`
    upsertMeta('meta[name="description"]', "name", "description", "A GitHub developer fingerprint generated by GridPath.")
    upsertMeta('meta[property="og:title"]', "property", "og:title", `${row.username} on GridPath`)
    upsertMeta('meta[property="og:description"]', "property", "og:description", "A GitHub developer fingerprint generated by GridPath.")
    upsertMeta('meta[property="og:image"]', "property", "og:image", row.card_url)
  }, [row, expired])

  if (loading) {
    return (
      <main className="shared-root">
        <div className="profile-content">
          <GlassPanel className="p-8">
            <p className="muted">Loading shared card…</p>
          </GlassPanel>
        </div>
      </main>
    )
  }

  if (error) {
    return (
      <main className="shared-root">
        <div className="profile-content">
          <GlassPanel as="section" className="p-8 shared-card-wrap">
            <h2 style={{ margin: "0 0 0.5rem", color: "var(--text-primary)" }}>Unable to load card</h2>
            <p className="error-text" style={{ margin: "0 0 1.25rem" }}>{error}</p>
            <Link className="btn btn-primary" to="/">Analyze your own profile</Link>
          </GlassPanel>
        </div>
      </main>
    )
  }

  if (!row || expired) {
    return (
      <main className="shared-root">
        <div className="profile-content">
          <GlassPanel as="section" className="p-8 shared-card-wrap">
            <h2 style={{ margin: "0 0 0.5rem", color: "var(--text-primary)" }}>This card has expired</h2>
            <p className="muted" style={{ margin: "0 0 1.25rem" }}>The share token is no longer valid.</p>
            <Link className="btn btn-primary" to="/">Analyze your own profile</Link>
          </GlassPanel>
        </div>
      </main>
    )
  }

  return (
    <main className="shared-root">
      <div className="profile-content">
        <GlassPanel as="section" className="p-6 shared-card-wrap">
          <h2 style={{ margin: "0 0 1rem", color: "var(--text-primary)" }}>@{row.username}</h2>
          <img src={row.card_url} alt="Shared GridPath card" className="shared-image" />
          <div style={{ marginTop: "1rem" }}>
            <Link className="btn btn-primary" to="/">Analyze your own profile</Link>
          </div>
        </GlassPanel>
      </div>
    </main>
  )
}
